services:
  lavinmq:
    image: cloudamqp/lavinmq:1.2.12
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=libbydev
    ports:
      - "5432:5432"
